-- KIRILGAYXXX BLOX FRUIT FARM
-- Автор: kirilgayxxx
-- Версия: 1.0

local player = game.Players.LocalPlayer
local char = player.Character
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")

-- ===== НАСТРОЙКИ =====
local Settings = {
    AutoFarm = true,
        AutoCollect = true,
            AutoQuest = true,
                AutoHeal = true,
                    FarmRadius = 50,
                        HealThreshold = 30
                        }

                        -- ===== МЕНЮ =====
                        local GUI = Instance.new("ScreenGui")
                        GUI.Name = "KirilGayXXX"
                        GUI.Parent = player.PlayerGui

                        local MainFrame = Instance.new("Frame")
                        MainFrame.Size = UDim2.new(0, 350, 0, 400)
                        MainFrame.Position = UDim2.new(0.5, -175, 0.5, -200)
                        MainFrame.BackgroundColor3 = Color3.fromRGB(15, 15, 25)
                        MainFrame.BackgroundTransparency = 0.05
                        MainFrame.BorderSizePixel = 0
                        MainFrame.Parent = GUI

                        -- Заголовок
                        local Title = Instance.new("TextLabel")
                        Title.Size = UDim2.new(1, 0, 0, 40)
                        Title.BackgroundColor3 = Color3.fromRGB(200, 50, 80)
                        Title.Text = "🔥 KIRILGAYXXX 🔥"
                        Title.TextColor3 = Color3.fromRGB(255, 255, 255)
                        Title.TextScaled = true
                        Title.Font = Enum.Font.Bold
                        Title.Parent = MainFrame

                        -- Контейнер
                        local ButtonContainer = Instance.new("ScrollingFrame")
                        ButtonContainer.Size = UDim2.new(1, -20, 1, -60)
                        ButtonContainer.Position = UDim2.new(0, 10, 0, 50)
                        ButtonContainer.BackgroundTransparency = 1
                        ButtonContainer.CanvasSize = UDim2.new(0, 0, 0, 350)
                        ButtonContainer.ScrollBarThickness = 5
                        ButtonContainer.Parent = MainFrame

                        -- Функция создания кнопки
                        local function createButton(text, callback, yPos)
                            local button = Instance.new("TextButton")
                                button.Size = UDim2.new(1, -10, 0, 35)
                                    button.Position = UDim2.new(0, 5, 0, yPos)
                                        button.BackgroundColor3 = Color3.fromRGB(50, 50, 80)
                                            button.Text = text
                                                button.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                    button.TextScaled = true
                                                        button.Font = Enum.Font.SourceSansBold
                                                            button.BorderSizePixel = 0
                                                                button.Parent = ButtonContainer
                                                                    
                                                                        button.MouseButton1Click:Connect(callback)
                                                                            return button
                                                                            end

                                                                            local yPos = 5
                                                                            createButton("🔄 AutoFarm", function()
                                                                                Settings.AutoFarm = not Settings.AutoFarm
                                                                                    print("KirilGayXXX: AutoFarm " .. tostring(Settings.AutoFarm))
                                                                                    end, yPos); yPos = yPos + 45

                                                                                    createButton("📦 AutoCollect", function()
                                                                                        Settings.AutoCollect = not Settings.AutoCollect
                                                                                            print("KirilGayXXX: AutoCollect " .. tostring(Settings.AutoCollect))
                                                                                            end, yPos); yPos = yPos + 45

                                                                                            createButton("📋 AutoQuest", function()
                                                                                                Settings.AutoQuest = not Settings.AutoQuest
                                                                                                    print("KirilGayXXX: AutoQuest " .. tostring(Settings.AutoQuest))
                                                                                                    end, yPos); yPos = yPos + 45

                                                                                                    createButton("💚 AutoHeal", function()
                                                                                                        Settings.AutoHeal = not Settings.AutoHeal
                                                                                                            print("KirilGayXXX: AutoHeal " .. tostring(Settings.AutoHeal))
                                                                                                            end, yPos); yPos = yPos + 45

                                                                                                            createButton("🏃 К NPC", function()
                                                                                                                local npc = findQuestNPC()
                                                                                                                    if npc then
                                                                                                                            char.HumanoidRootPart.CFrame = npc.HumanoidRootPart.CFrame + Vector3.new(0, 0, 5)
                                                                                                                                end
                                                                                                                                end, yPos); yPos = yPos + 45

                                                                                                                                -- Кнопка закрытия
                                                                                                                                local CloseButton = Instance.new("TextButton")
                                                                                                                                CloseButton.Size = UDim2.new(0, 30, 0, 30)
                                                                                                                                CloseButton.Position = UDim2.new(1, -35, 0, 5)
                                                                                                                                CloseButton.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
                                                                                                                                CloseButton.Text = "✕"
                                                                                                                                CloseButton.TextColor3 = Color3.fromRGB(255, 255, 255)
                                                                                                                                CloseButton.TextScaled = true
                                                                                                                                CloseButton.Font = Enum.Font.Bold
                                                                                                                                CloseButton.BorderSizePixel = 0
                                                                                                                                CloseButton.Parent = MainFrame

                                                                                                                                CloseButton.MouseButton1Click:Connect(function()
                                                                                                                                    MainFrame.Visible = not MainFrame.Visible
                                                                                                                                    end)

                                                                                                                                    -- ===== ФУНКЦИИ =====

                                                                                                                                    local function getClosestMob()
                                                                                                                                        local closestMob = nil
                                                                                                                                            local closestDistance = math.huge
                                                                                                                                                
                                                                                                                                                    for _, mob in pairs(workspace:GetChildren()) do
                                                                                                                                                            if mob:FindFirstChild("Humanoid") and mob:FindFirstChild("HumanoidRootPart") then
                                                                                                                                                                        if mob.Humanoid.Health > 0 and not mob:IsA("Player") then
                                                                                                                                                                                        local distance = (mob.HumanoidRootPart.Position - char.HumanoidRootPart.Position).Magnitude
                                                                                                                                                                                                        if distance < closestDistance and distance < Settings.FarmRadius then
                                                                                                                                                                                                                            closestMob = mob
                                                                                                                                                                                                                                                closestDistance = distance
                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                return closestMob
                                                                                                                                                                                                                                                                                                end

                                                                                                                                                                                                                                                                                                local function findQuestNPC()
                                                                                                                                                                                                                                                                                                    for _, npc in pairs(workspace:GetChildren()) do
                                                                                                                                                                                                                                                                                                            if npc:FindFirstChild("Humanoid") and npc.Name:find("Quest") then
                                                                                                                                                                                                                                                                                                                        return npc
                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                                                                        return nil
                                                                                                                                                                                                                                                                                                                                        end

                                                                                                                                                                                                                                                                                                                                        local function attackMob(mob)
                                                                                                                                                                                                                                                                                                                                            if not mob then return end
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                    char.HumanoidRootPart.CFrame = CFrame.new(char.HumanoidRootPart.Position, mob.HumanoidRootPart.Position)
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                            local remote = game:GetService("ReplicatedStorage"):FindFirstChild("Remotes"):FindFirstChild("Attack")
                                                                                                                                                                                                                                                                                                                                                                if remote then
                                                                                                                                                                                                                                                                                                                                                                        remote:FireServer(mob)
                                                                                                                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                                                                                                                            end

                                                                                                                                                                                                                                                                                                                                                                            local function collectDrops()
                                                                                                                                                                                                                                                                                                                                                                                for _, drop in pairs(workspace:GetChildren()) do
                                                                                                                                                                                                                                                                                                                                                                                        if drop:IsA("Tool") or drop:IsA("Part") and drop.Name:find("Drop") then
                                                                                                                                                                                                                                                                                                                                                                                                    if drop:FindFirstChild("ClickDetector") then
                                                                                                                                                                                                                                                                                                                                                                                                                    fireclickdetector(drop.ClickDetector)
                                                                                                                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                                                                                                                                                                                            end

                                                                                                                                                                                                                                                                                                                                                                                                                                            -- ===== ОСНОВНОЙ ЦИКЛ =====

                                                                                                                                                                                                                                                                                                                                                                                                                                            RunService.Heartbeat:Connect(function()
                                                                                                                                                                                                                                                                                                                                                                                                                                                if not char or not char:FindFirstChild("HumanoidRootPart") then return end
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if Settings.AutoFarm then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                local mob = getClosestMob()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if mob then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    attackMob(mob)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if Settings.AutoCollect then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                collectDrops()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if Settings.AutoQuest then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local npc = findQuestNPC()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if npc then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        char.HumanoidRootPart.CFrame = npc.HumanoidRootPart.CFrame + Vector3.new(0, 0, 5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if Settings.AutoHeal and char.Humanoid.Health < Settings.HealThreshold then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local healTool = player.Backpack:FindFirstChild("Heal")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if healTool then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        char.Humanoid:EquipTool(healTool)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    healTool:Activate()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- ===== ГОРЯЧИЕ КЛАВИШИ =====

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                UserInputService.InputBegan:Connect(function(input, gameProcessed)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if gameProcessed then return end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if input.KeyCode == Enum.KeyCode.F3 then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    MainFrame.Visible = not MainFrame.Visible
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elseif input.KeyCode == Enum.KeyCode.F1 then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Settings.AutoFarm = not Settings.AutoFarm
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elseif input.KeyCode == Enum.KeyCode.F2 then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Settings.AutoQuest = not Settings.AutoQuest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- ===== ПОДСКАЗКА =====

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                local Hint = Instance.new("TextLabel")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.Size = UDim2.new(0, 250, 0, 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.Position = UDim2.new(0, 10, 1, -40)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.BackgroundTransparency = 0.5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.Text = "🔥 KIRILGAYXXX | F3 - Меню"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.TextColor3 = Color3.fromRGB(255, 200, 200)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.TextScaled = true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.Font = Enum.Font.SourceSansBold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hint.Parent = player.PlayerGui

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("✅ KIRILGAYXXX ЗАГРУЖЕН!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("📌 F1 - AutoFarm | F2 - AutoQuest | F3 - Меню")